version = 0.1

[default.global.parameters]
stack_name = "secretshare"
region = "eu-north-1"

[default.build.parameters]
beta_features = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
